import type { GlobalConfig } from 'payload'

const faqDefaults = [
  {
    enabled: true,
    questionPT: 'Onde entregam e quanto tempo demora?',
    questionEN: 'Where do you deliver and how long does it take?',
    answerPT: 'Entregamos por estafeta local nos 16 municípios de Luanda. O custo é calculado pela localização e apresentado no checkout; depois da confirmação, a equipa coordena consigo o horário de entrega. Não prometemos um prazo de 24 horas sem confirmação prévia.',
    answerEN: 'We deliver by local courier across Luanda’s 16 municipalities. The fee is calculated from your location and shown at checkout; after confirmation, our team coordinates the delivery time. We do not promise 24-hour delivery without prior confirmation.',
    answerPTPT: 'Em Portugal enviamos pelos CTT. Pode escolher envio Standard sem rastreio ou Registado com rastreio, quando disponível para o peso da encomenda. O custo e o prazo estimado dependem do destino; Madeira e Açores podem demorar mais.',
    answerENPT: 'In Portugal we ship with CTT. You can choose Standard untracked or Registered tracked delivery when available for the parcel weight. Cost and estimated timing depend on the destination; Madeira and the Azores may take longer.',
  },
  {
    enabled: true,
    questionPT: 'Quanto custa a entrega?',
    questionEN: 'How much does delivery cost?',
    answerPT: 'O valor exato é calculado no checkout antes de confirmar. A entrega é gratuita a partir de 80 000 Kz, depois de descontos. Também fazemos envios internacionais; contacte o apoio para confirmar custo e prazo para o seu país.',
    answerEN: 'The exact fee is calculated at checkout before you confirm. Delivery is free from 80,000 Kz, after discounts. International shipping is also available; contact support to confirm the cost and timing for your country.',
    answerPTPT: 'O valor exato é calculado no checkout antes de confirmar. A entrega é gratuita a partir de 75 €, depois de descontos. Também fazemos envios internacionais; contacte o apoio para confirmar custo e prazo para o seu país.',
    answerENPT: 'The exact fee is calculated at checkout before you confirm. Delivery is free from €75, after discounts. International shipping is also available; contact support to confirm the cost and timing for your country.',
  },
  {
    enabled: true,
    questionPT: 'Que métodos de pagamento aceitam?',
    questionEN: 'Which payment methods do you accept?',
    answerPT: 'Na loja Angola, o checkout apresenta o AppyPay para pagamento por Multicaixa Express ou Referência. A encomenda só fica confirmada depois de o pagamento ser verificado.',
    answerEN: 'In the Angola store, checkout presents AppyPay for Multicaixa Express or payment by Reference. Your order is confirmed only after the payment is verified.',
    answerPTPT: 'Na loja Portugal, o pagamento é atualmente coordenado por email após a criação da encomenda. Quando os pagamentos online estiverem ativos, o checkout mostrará apenas os métodos disponíveis.',
    answerENPT: 'In the Portugal store, payment is currently coordinated by email after the order is created. When online payments are active, checkout will show only the available methods.',
  },
  {
    enabled: true,
    questionPT: 'Como escolho o tamanho certo?',
    questionEN: 'How do I choose the right size?',
    answerPT: 'Abra a página do produto e consulte o guia de tamanhos associado à peça. Compare as suas medidas com a tabela e leia a nota de ajuste quando existir. Se continuar com dúvidas, contacte o apoio antes de encomendar.',
    answerEN: 'Open the product page and use the size guide assigned to that item. Compare your measurements with the table and read the fit note when one is provided. If you are still unsure, contact support before ordering.',
    linkPath: '/guia-de-tamanhos',
    linkLabelPT: 'Consultar o guia de tamanhos',
    linkLabelEN: 'View the size guide',
  },
  {
    enabled: true,
    questionPT: 'Posso trocar ou devolver um artigo?',
    questionEN: 'Can I exchange or return an item?',
    answerPT: 'Em Angola, comunique qualquer pedido de troca no prazo máximo de 48 horas após receber a encomenda. A elegibilidade, o estado exigido do artigo, os custos e as exceções constam da política completa.',
    answerEN: 'In Angola, tell us about an exchange request within 48 hours of receiving the order. Eligibility, required item condition, costs, and exceptions are explained in the full policy.',
    answerPTPT: 'Em Portugal, as compras online dispõem do prazo legal indicado na nossa política para comunicar a intenção de devolução. O artigo deve cumprir as condições descritas na política completa.',
    answerENPT: 'In Portugal, online purchases have the legal period stated in our policy to notify us of an intended return. The item must meet the conditions described in the full policy.',
    linkPath: '/ajuda#devolucoes',
    linkLabelPT: 'Ler a política de trocas e devoluções',
    linkLabelEN: 'Read the returns and exchanges policy',
  },
  {
    enabled: true,
    questionPT: 'Como acompanho a minha encomenda?',
    questionEN: 'How do I track my order?',
    answerPT: 'Use o número da encomenda e o email utilizado na compra na página Consultar encomenda.',
    answerEN: 'Use the order number and the email used at checkout on the Track order page.',
    answerPTPT: 'Use o número da encomenda e o email utilizado na compra na página Consultar encomenda. Em Portugal, o código e o link de rastreio CTT aparecem depois de a encomenda ser enviada, quando o serviço escolhido inclui rastreio.',
    answerENPT: 'Use the order number and the email used at checkout on the Track order page. In Portugal, the CTT tracking code and link appear after dispatch when your selected service includes tracking.',
    linkPath: '/conta',
    linkLabelPT: 'Consultar encomenda',
    linkLabelEN: 'Track order',
  },
]

const aboutValueDefaults = [
  {
    enabled: true,
    titlePT: 'Qualidade em primeiro lugar',
    titleEN: 'Quality first',
    bodyPT: 'Cada peça é escolhida para durar mais do que uma estação.',
    bodyEN: 'Every piece is chosen to outlast a single season.',
  },
  {
    enabled: true,
    titlePT: 'Preços diretos',
    titleEN: 'Honest pricing',
    bodyPT: 'Sem letras pequenas — o preço que vê é o preço que paga.',
    bodyEN: 'No fine print — the price you see is the price you pay.',
  },
  {
    enabled: true,
    titlePT: 'Perto de si',
    titleEN: 'Close to you',
    bodyPT: 'Duas lojas, uma só marca: Angola e Portugal, cada uma com o seu atendimento.',
    bodyEN: 'Two storefronts, one brand: Angola and Portugal, each with its own local service.',
  },
]

export const StorefrontContent: GlobalConfig = {
  slug: 'storefront-content',
  label: 'Storefront content',
  access: { read: () => true },
  admin: {
    group: 'Settings',
    description: 'Homepage SEO, About, FAQ and standalone size-guide page copy. Day-to-day editing is available in the custom storefront admin.',
  },
  fields: [
    { name: 'homeSeoTitleAngolaPT', type: 'text', defaultValue: 'Moda desportiva feminina em Luanda | Use Me With Style' },
    { name: 'homeSeoTitleAngolaEN', type: 'text', defaultValue: "Women's activewear in Luanda | Use Me With Style" },
    { name: 'homeSeoDescriptionAngolaPT', type: 'textarea', defaultValue: 'Compre moda desportiva feminina com entrega em Luanda e pagamento por Multicaixa Express ou Referência. Preços em Kz e apoio local.' },
    { name: 'homeSeoDescriptionAngolaEN', type: 'textarea', defaultValue: "Shop women's activewear with delivery across Luanda and payment by Multicaixa Express or Reference. Prices in Kz and local support." },
    { name: 'homeSeoTitlePortugalPT', type: 'text', defaultValue: 'Moda desportiva feminina em Portugal | Use Me With Style' },
    { name: 'homeSeoTitlePortugalEN', type: 'text', defaultValue: "Women's activewear in Portugal | Use Me With Style" },
    { name: 'homeSeoDescriptionPortugalPT', type: 'textarea', defaultValue: 'Compre leggings, conjuntos, tops e vestidos com entrega em Portugal. Peças versáteis para treino e para o dia a dia.' },
    { name: 'homeSeoDescriptionPortugalEN', type: 'textarea', defaultValue: 'Shop leggings, sets, tops and dresses with delivery across Portugal. Versatile pieces for training and everyday wear.' },
    { name: 'aboutEyebrowPT', type: 'text', defaultValue: 'Use Me With Style' },
    { name: 'aboutEyebrowEN', type: 'text', defaultValue: 'Use Me With Style' },
    { name: 'aboutTitlePT', type: 'text', defaultValue: 'A nossa história' },
    { name: 'aboutTitleEN', type: 'text', defaultValue: 'Our story' },
    { name: 'aboutIntroPT', type: 'textarea', defaultValue: 'A USE ME WITH STYLE é uma marca de activewear, moda feminina e lifestyle, criada para mulheres que valorizam conforto, confiança, elegância e versatilidade.' },
    { name: 'aboutIntroEN', type: 'textarea', defaultValue: 'USE ME WITH STYLE is an activewear, women’s fashion, and lifestyle brand created for women who value comfort, confidence, elegance, and versatility.' },
    { name: 'aboutStoryTitlePT', type: 'text', defaultValue: 'Missão' },
    { name: 'aboutStoryTitleEN', type: 'text', defaultValue: 'Mission' },
    { name: 'aboutStoryBodyPT', type: 'textarea', defaultValue: 'A marca disponibiliza peças pensadas para diferentes momentos da rotina feminina, desde o treino e o dia a dia até ocasiões que pedem um visual mais elegante. O nosso catálogo inclui conjuntos desportivos, peças casuais, vestidos e outros artigos selecionados para proporcionar conforto sem perder o estilo.\n\nCom atuação em Angola e Portugal e possibilidade de envios internacionais, a USE ME WITH STYLE procura aproximar mulheres de diferentes lugares através de coleções cuidadosamente selecionadas e disponibilizadas em quantidades limitadas.\n\nMais do que roupa, a USE ME WITH STYLE representa uma forma de vestir com confiança, personalidade e liberdade.' },
    { name: 'aboutStoryBodyEN', type: 'textarea', defaultValue: "The brand offers pieces designed for different moments in a woman's routine, from workouts and everyday life to occasions that call for a more elegant look. Our catalogue includes activewear sets, casual pieces, dresses, and other selected items designed to deliver comfort without compromising on style.\n\nWith a presence in Angola and Portugal and international shipping available, USE ME WITH STYLE brings women from different places closer together through carefully curated collections released in limited quantities.\n\nMore than just clothing, USE ME WITH STYLE represents a way of dressing with confidence, personality, and freedom." },
    { name: 'aboutValuesTitlePT', type: 'text', defaultValue: 'O que nos guia' },
    { name: 'aboutValuesTitleEN', type: 'text', defaultValue: 'What guides us' },
    {
      name: 'aboutValues',
      type: 'array',
      defaultValue: aboutValueDefaults,
      labels: { singular: 'Brand value', plural: 'Brand values' },
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'titlePT', type: 'text', required: true },
        { name: 'titleEN', type: 'text', required: true },
        { name: 'bodyPT', type: 'textarea', required: true },
        { name: 'bodyEN', type: 'textarea', required: true },
      ],
    },
    { name: 'aboutPresenceTitlePT', type: 'text', defaultValue: 'Angola e Portugal, perto de si' },
    { name: 'aboutPresenceTitleEN', type: 'text', defaultValue: 'Angola and Portugal, close to you' },
    { name: 'aboutAngolaTitlePT', type: 'text', defaultValue: 'Loja Angola' },
    { name: 'aboutAngolaTitleEN', type: 'text', defaultValue: 'Angola store' },
    { name: 'aboutAngolaBodyPT', type: 'textarea', defaultValue: 'Na loja Angola, encontra preços em Kz, entrega por estafeta nos 16 municípios de Luanda e pagamento por Multicaixa Express ou Referência. Para outros destinos, o apoio confirma as opções disponíveis.' },
    { name: 'aboutAngolaBodyEN', type: 'textarea', defaultValue: 'In the Angola store, prices are shown in Kz, with courier delivery across Luanda’s 16 municipalities and payment by Multicaixa Express or Reference. For other destinations, support confirms the available options.' },
    { name: 'aboutPortugalTitlePT', type: 'text', defaultValue: 'Loja Portugal' },
    { name: 'aboutPortugalTitleEN', type: 'text', defaultValue: 'Portugal store' },
    { name: 'aboutPortugalBodyPT', type: 'textarea', defaultValue: 'Na loja Portugal, compra em euros e recebe via CTT, com opções Standard ou Registado quando disponíveis para o peso da encomenda. Madeira e Açores podem ter prazos diferentes.' },
    { name: 'aboutPortugalBodyEN', type: 'textarea', defaultValue: 'In the Portugal store, you shop in euros and receive orders through CTT, with Standard or Registered options when available for the parcel weight. Madeira and the Azores may have different delivery times.' },
    { name: 'aboutCtaLabelPT', type: 'text', defaultValue: 'Ver a coleção' },
    { name: 'aboutCtaLabelEN', type: 'text', defaultValue: 'Shop the collection' },
    { name: 'aboutSeoTitlePT', type: 'text', defaultValue: 'Moda desportiva em Angola e Portugal | Use Me With Style' },
    { name: 'aboutSeoTitleEN', type: 'text', defaultValue: 'Activewear in Angola and Portugal | Use Me With Style' },
    { name: 'aboutSeoDescriptionPT', type: 'textarea', defaultValue: 'Conheça a história e os valores da Use Me With Style, marca de activewear e moda feminina com presença em Angola e Portugal.' },
    { name: 'aboutSeoDescriptionEN', type: 'textarea', defaultValue: 'Discover the story and values of Use Me With Style, an activewear and women’s fashion brand serving Angola and Portugal.' },
    { name: 'faqTitlePT', type: 'text', defaultValue: 'Perguntas frequentes' },
    { name: 'faqTitleEN', type: 'text', defaultValue: 'Frequently asked questions' },
    { name: 'faqIntroPT', type: 'textarea', defaultValue: 'Encontre informação prática antes de encomendar. As condições apresentadas acompanham a loja e o mercado que está a visitar.' },
    { name: 'faqIntroEN', type: 'textarea', defaultValue: 'Find practical information before ordering. The details below follow the store and market you are currently visiting.' },
    { name: 'faqSupportPromptPT', type: 'text', defaultValue: 'Não encontrou a resposta?' },
    { name: 'faqSupportPromptEN', type: 'text', defaultValue: 'Couldn’t find your answer?' },
    { name: 'faqSupportLabelPT', type: 'text', defaultValue: 'Contacte o apoio.' },
    { name: 'faqSupportLabelEN', type: 'text', defaultValue: 'Contact support.' },
    { name: 'faqSeoTitlePT', type: 'text', defaultValue: 'Perguntas frequentes | Use Me With Style' },
    { name: 'faqSeoTitleEN', type: 'text', defaultValue: 'Frequently asked questions | Use Me With Style' },
    { name: 'faqSeoDescriptionPT', type: 'textarea', defaultValue: 'Respostas sobre entregas, pagamentos, tamanhos, trocas e devoluções da Use Me With Style em Angola e Portugal.' },
    { name: 'faqSeoDescriptionEN', type: 'textarea', defaultValue: 'Answers about Use Me With Style delivery, payments, sizing, exchanges, and returns in Angola and Portugal.' },
    {
      name: 'faqEntries',
      type: 'array',
      defaultValue: faqDefaults,
      labels: { singular: 'FAQ entry', plural: 'FAQ entries' },
      fields: [
        { name: 'enabled', type: 'checkbox', defaultValue: true },
        { name: 'questionPT', type: 'text', required: true },
        { name: 'questionEN', type: 'text', required: true },
        { name: 'answerPT', type: 'textarea', required: true, label: 'Answer — Portuguese (Angola and fallback)' },
        { name: 'answerEN', type: 'textarea', required: true, label: 'Answer — English (Angola and fallback)' },
        { name: 'answerPTPT', type: 'textarea', label: 'Portugal override — Portuguese' },
        { name: 'answerENPT', type: 'textarea', label: 'Portugal override — English' },
        { name: 'linkPath', type: 'text', admin: { description: 'Optional internal path, e.g. /ajuda#devolucoes.' } },
        { name: 'linkLabelPT', type: 'text' },
        { name: 'linkLabelEN', type: 'text' },
      ],
    },
    { name: 'sizeGuideTitlePT', type: 'text', defaultValue: 'Guia de tamanhos' },
    { name: 'sizeGuideTitleEN', type: 'text', defaultValue: 'Size guide' },
    { name: 'sizeGuideIntroPT', type: 'textarea', defaultValue: 'Encontre o tamanho certo para leggings, tops, vestidos e conjuntos. Tire as suas medidas sem apertar a fita e compare-as, em centímetros, com a tabela da categoria da peça.' },
    { name: 'sizeGuideIntroEN', type: 'textarea', defaultValue: 'Find the right size for leggings, tops, dresses and sets. Take your measurements without pulling the tape tight, then compare them in centimetres with the chart for your item category.' },
    { name: 'sizeGuideHowToTitlePT', type: 'text', defaultValue: 'Como medir' },
    { name: 'sizeGuideHowToTitleEN', type: 'text', defaultValue: 'How to measure' },
    { name: 'sizeGuideBustPT', type: 'text', defaultValue: 'Busto: meça à volta da parte mais larga do peito.' },
    { name: 'sizeGuideBustEN', type: 'text', defaultValue: 'Bust: measure around the fullest part of your chest.' },
    { name: 'sizeGuideWaistPT', type: 'text', defaultValue: 'Cintura: meça à volta da parte mais estreita do tronco.' },
    { name: 'sizeGuideWaistEN', type: 'text', defaultValue: 'Waist: measure around the narrowest part of your torso.' },
    { name: 'sizeGuideHipPT', type: 'text', defaultValue: 'Anca: meça à volta da parte mais larga das ancas.' },
    { name: 'sizeGuideHipEN', type: 'text', defaultValue: 'Hip: measure around the fullest part of your hips.' },
    { name: 'sizeGuideLengthPT', type: 'text', defaultValue: 'Comprimento: compare com o comprimento indicado para a peça; o ponto inicial varia conforme o tipo de produto.' },
    { name: 'sizeGuideLengthEN', type: 'text', defaultValue: 'Length: compare with the garment length shown; the starting point varies by product type.' },
    { name: 'sizeGuideClosingPT', type: 'textarea', defaultValue: 'A tabela associada à página de cada produto é sempre a referência principal. Entre dois tamanhos ou ainda com dúvidas?' },
    { name: 'sizeGuideClosingEN', type: 'textarea', defaultValue: 'The chart assigned to each product page is always the primary reference. Between sizes or still unsure?' },
    { name: 'sizeGuideSupportLabelPT', type: 'text', defaultValue: 'Fale connosco' },
    { name: 'sizeGuideSupportLabelEN', type: 'text', defaultValue: 'Contact us' },
    { name: 'sizeGuideCatalogLabelPT', type: 'text', defaultValue: 'Explorar o catálogo' },
    { name: 'sizeGuideCatalogLabelEN', type: 'text', defaultValue: 'Browse the catalogue' },
    { name: 'sizeGuideSeoTitlePT', type: 'text', defaultValue: 'Guia de tamanhos | Use Me With Style' },
    { name: 'sizeGuideSeoTitleEN', type: 'text', defaultValue: 'Size guide | Use Me With Style' },
    { name: 'sizeGuideSeoDescriptionPT', type: 'textarea', defaultValue: 'Consulte o guia de tamanhos de leggings, tops, vestidos e conjuntos Use Me With Style e compare busto, cintura e anca em centímetros.' },
    { name: 'sizeGuideSeoDescriptionEN', type: 'textarea', defaultValue: 'Use our size guide for leggings, tops, dresses and sets, and compare bust, waist and hip measurements in centimetres.' },
  ],
}
