import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'

// This migration's real schema-creation SQL was generated by `payload
// migrate:create` and applied directly against the production Railway
// Postgres database on 2026-07-08 (via the Railway console, to unblock the
// very first deploy -- see JOS media-storage/production-readiness work).
// That generated file only ever existed in the deploy container's ephemeral
// filesystem and wasn't retrievable back out of it, so this checked-in copy
// is a placeholder with the SAME migration name rather than a byte-for-byte
// copy of the original SQL.
//
// Why this is safe: Payload tracks which migrations have run by NAME only
// (see payload/dist/database/migrations/getMigrations.js -- it queries the
// `payload-migrations` collection for existing migration names, no content
// hash involved). Production already has a `payload-migrations` row named
// "20260708_220620_initial", so `payload migrate` will see this file, match
// the name, and skip it -- it will NOT try to re-run `up` and re-create
// tables that already exist.
//
// If you ever need the real, full CREATE TABLE SQL (e.g. to provision a
// fresh environment from scratch, or to actually roll back), regenerate it
// with `payload migrate:create` pointed at an empty Postgres database --
// it's a deterministic diff against the current collections in
// payload.config.ts, so it will reproduce the same schema.
export async function up({ payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  // No-op: schema already created directly in production. See comment above.
}

export async function down({ payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  // No-op: this placeholder has no reverse migration. Regenerate a real
  // migration (see comment above) before relying on rollback.
}
