/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    'merch-tags': MerchTag;
    colors: Color;
    'size-guides': SizeGuide;
    posts: Post;
    orders: Order;
    customers: Customer;
    messages: Message;
    invoices: Invoice;
    coupons: Coupon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'merch-tags': MerchTagsSelect<false> | MerchTagsSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    'size-guides': SizeGuidesSelect<false> | SizeGuidesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'market-settings': MarketSetting;
    'invoice-settings': InvoiceSetting;
    'legal-content': LegalContent;
    'home-hero': HomeHero;
    'home-categories': HomeCategory;
    'home-collections': HomeCollection;
    'instagram-spotlight': InstagramSpotlight;
    'ai-messaging-settings': AiMessagingSetting;
    'storefront-content': StorefrontContent;
  };
  globalsSelect: {
    'market-settings': MarketSettingsSelect<false> | MarketSettingsSelect<true>;
    'invoice-settings': InvoiceSettingsSelect<false> | InvoiceSettingsSelect<true>;
    'legal-content': LegalContentSelect<false> | LegalContentSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-categories': HomeCategoriesSelect<false> | HomeCategoriesSelect<true>;
    'home-collections': HomeCollectionsSelect<false> | HomeCollectionsSelect<true>;
    'instagram-spotlight': InstagramSpotlightSelect<false> | InstagramSpotlightSelect<true>;
    'ai-messaging-settings': AiMessagingSettingsSelect<false> | AiMessagingSettingsSelect<true>;
    'storefront-content': StorefrontContentSelect<false> | StorefrontContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload guidance: products/categories up to 2 MB and 2000px wide; homepage hero images up to 3 MB and 2560px wide; logos/icons up to 500 KB.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required: describe what is visible. For product photos include the product, colour/view and product type; do not use the filename.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Internal/default product name (kept aligned with the Portuguese name).
   */
  name: string;
  namePT?: string | null;
  nameEN?: string | null;
  /**
   * Auto-generated from the product name -- not editable (2026-07-25 admin request). See generateProductSlug in src/lib/productSlug.ts.
   */
  slug: string;
  category: number | Category;
  /**
   * Standard products own stock variants. Product kits derive availability from their component variants.
   */
  productType: 'standard' | 'bundle';
  /**
   * Legacy/default description. New storefront editing uses the language-specific fields below.
   */
  description?: string | null;
  descriptionPT?: string | null;
  descriptionEN?: string | null;
  /**
   * Product checklist: assign a shared measurement chart to every standard apparel product with clothing sizes. Leave blank only for accessories or products where measurements do not apply. Used on product pages and the public size-guide page.
   */
  sizeGuide?: (number | null) | SizeGuide;
  /**
   * Optional short per-product advice shown under the size chart, e.g. "Veste pequeno, recomendamos um tamanho acima."
   */
  fitNotePT?: string | null;
  fitNoteEN?: string | null;
  /**
   * Optional. Examples: Tamanho, Capacidade, Estilo. Leave empty when the product has no non-colour option.
   */
  optionLabelPT?: string | null;
  /**
   * Optional. Examples: Size, Capacity, Style.
   */
  optionLabelEN?: string | null;
  /**
   * Reusable customer-facing facts such as material, capacity, dimensions, care or fit.
   */
  specifications?:
    | {
        labelPT: string;
        labelEN?: string | null;
        valuePT: string;
        valueEN?: string | null;
        id?: string | null;
      }[]
    | null;
  returnEligible?: boolean | null;
  returnNotePT?: string | null;
  returnNoteEN?: string | null;
  /**
   * Optional merchandising badge(s) shown on the product card.
   */
  tag?: (number | MerchTag)[] | null;
  images?:
    | {
        image: number | Media;
        /**
         * Optional. Leave blank for a general photo shown for every colour. Set this to show the photo only when this colour is selected.
         */
        color?: (number | null) | Color;
        id?: string | null;
      }[]
    | null;
  priceAOKz: number;
  pricePTEur: number;
  /**
   * Used to calculate Portugal parcel shipping. Include normal product packaging.
   */
  shippingWeightGrams: number;
  /**
   * Optional. Replaces the regular Angola price while set and within the sale window (if any).
   */
  saleAOKz?: number | null;
  /**
   * Optional. Replaces the regular Portugal price while set and within the sale window (if any).
   */
  salePTEur?: number | null;
  /**
   * Optional. Leave blank for the sale to be active immediately.
   */
  saleStartDate?: string | null;
  /**
   * Optional. Leave blank for the sale to run indefinitely.
   */
  saleEndDate?: string | null;
  /**
   * One row per sellable combination, with per-market stock.
   */
  variants?:
    | {
        sku?: string | null;
        color?: (number | null) | Color;
        /**
         * Examples: XS, 750 ml, Ajustável. Leave empty for a colour-only or option-less product.
         */
        size?: string | null;
        optionValueEN?: string | null;
        stockAO: number;
        stockPT: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Fixed contents of this kit. Stock is derived from and deducted from these component variants.
   */
  bundleComponents?:
    | {
        product: number | Product;
        variantId: string;
        qty: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Unpublish to hide from the storefront without deleting it.
   */
  active?: boolean | null;
  /**
   * Uncheck to hide this product from the Angola storefront entirely.
   */
  availableAO?: boolean | null;
  /**
   * Uncheck to hide this product from the Portugal storefront entirely.
   */
  availablePT?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  namePT: string;
  /**
   * Shown when the shopper switches the storefront to English. Falls back to the Portuguese name if empty.
   */
  nameEN?: string | null;
  /**
   * Shown below the category filters when this is the only active category. Keep it concise and useful to shoppers.
   */
  introPT?: string | null;
  /**
   * English version of the catalogue introduction. Falls back to Portuguese if empty.
   */
  introEN?: string | null;
  /**
   * Auto-generated from the Portuguese name; used in storefront URLs (/catalogo?cat=...). Not editable.
   */
  slug?: string | null;
  /**
   * Shown on the home page's category tiles. Optional -- falls back to a decorative placeholder when unset.
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-guides".
 */
export interface SizeGuide {
  id: number;
  /**
   * Internal name, e.g. "Vestidos — padrão". Shoppers never see this.
   */
  name: string;
  /**
   * One row per size. All measurements in centimetres; leave blank any that do not apply to this garment type.
   */
  rows: {
    size: 'XS' | 'S' | 'M' | 'L' | 'XL';
    bust?: number | null;
    waist?: number | null;
    hip?: number | null;
    length?: number | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch-tags".
 */
export interface MerchTag {
  id: number;
  /**
   * Badge text shown on product cards, e.g. "Novidade".
   */
  labelPT: string;
  /**
   * Shown on the English storefront. Falls back to the Portuguese label if empty.
   */
  labelEN?: string | null;
  /**
   * Auto-generated from the Portuguese label; usable as a storefront "collection" link (/catalogo?tag=...). Not editable.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  /**
   * Display name, e.g. "Verde Oliva".
   */
  namePT: string;
  /**
   * Shown when the shopper switches the storefront to English. Falls back to the Portuguese name if empty.
   */
  nameEN?: string | null;
  /**
   * Solid-colour swatch, e.g. #7A8B5C. Leave empty for patterned fabrics and upload a swatch image instead.
   */
  hex?: string | null;
  /**
   * Optional. Set this to create a two-tone combination colour -- the swatch renders as a split circle.
   */
  hex2?: string | null;
  /**
   * Optional. For patterns/multicolour fabrics where a single hex value is not representative. Takes precedence over the hex value.
   */
  swatch?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bilingual editorial articles. Day-to-day editing is also available in the custom storefront admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titlePT: string;
  titleEN: string;
  /**
   * Generated from the Portuguese title and kept stable after publication.
   */
  slug: string;
  excerptPT: string;
  excerptEN: string;
  /**
   * Structured rich content. Blocks can be reordered and edited bilingually in the storefront admin.
   */
  body: {
    kind: 'section' | 'paragraph' | 'bullets';
    headingPT?: string | null;
    headingEN?: string | null;
    textPT: string;
    textEN: string;
    id?: string | null;
  }[];
  seoTitlePT: string;
  seoTitleEN: string;
  seoDescriptionPT: string;
  seoDescriptionEN: string;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  availableAO: boolean;
  availablePT: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  market: 'AO' | 'PT';
  status?: ('new' | 'payment_review' | 'processing' | 'shipped' | 'delivered' | 'cancelled') | null;
  customerName: string;
  customerFirstName?: string | null;
  customerLastName?: string | null;
  customerPhone: string;
  customerEmail: string;
  analyticsConsent?: boolean | null;
  metaFbp?: string | null;
  metaFbc?: string | null;
  metaEventSourceUrl?: string | null;
  /**
   * Storefront language the customer had selected at checkout -- determines the language of the order-confirmation email.
   */
  lang?: ('pt' | 'en') | null;
  address: string;
  /**
   * House number, floor/door, or other locator info -- collected for both Angola and Portugal orders since 2026-08-04.
   */
  addressLine2: string;
  /**
   * CTT format 0000-000 -- validated client-side on the PT storefront, not collected for Angola.
   */
  postalCode?: string | null;
  /**
   * Classified automatically from the Portuguese postal code when the order is created.
   */
  deliveryRegion?: ('mainland' | 'madeira' | 'azores') | null;
  city: string;
  country: string;
  /**
   * Customer tax number, optional -- snapshotted onto the internal commercial invoice for accounting review.
   */
  taxId?: string | null;
  notes?: string | null;
  items: {
    product: number | Product;
    productName: string;
    variantId?: string | null;
    size?: string | null;
    optionLabel?: string | null;
    optionValue?: string | null;
    color?: string | null;
    colorId?: string | null;
    productType?: ('standard' | 'bundle') | null;
    inventoryComponents?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    qty: number;
    unitPrice: number;
    regularUnitPrice?: number | null;
    saleDiscountAmount?: number | null;
    saleDiscountPercentage?: number | null;
    id?: string | null;
  }[];
  currency: 'Kz' | 'EUR';
  subtotal: number;
  shippingCost: number;
  /**
   * Snapshot of the coupon code used, if any.
   */
  couponCode?: string | null;
  /**
   * Amount deducted by the coupon, in the order currency.
   */
  discountAmount?: number | null;
  /**
   * Human-readable label shown on the invoice/admin, e.g. "SS26 (10% off)".
   */
  discountLabel?: string | null;
  total: number;
  paymentMethod:
    'paypal' | 'stripe' | 'mbway' | 'multicaixa_express' | 'manual_whatsapp' | 'bank_transfer_ao' | 'sweg_appypay';
  paymentStatus?: ('pending' | 'awaiting_manual_review' | 'paid' | 'failed') | null;
  inventoryReservationStatus?: ('none' | 'active' | 'committed' | 'released') | null;
  inventoryReservationExpiresAt?: string | null;
  inventoryReservationReleasedAt?: string | null;
  deliveryMethod: 'ctt' | 'courier_pt' | 'courier_ao' | 'manual_ao';
  /**
   * For CTT Registered orders, enter the code from the CTT receipt or shipping portal. It becomes visible in the customer order lookup.
   */
  cttTrackingCode?: string | null;
  /**
   * Provider transaction ID (Stripe, PayPal or AppyPay) -- set automatically for admin troubleshooting.
   */
  paymentReference?: string | null;
  /**
   * Our <=15 character alphanumeric transaction ID sent to the AppyPay widget and echoed by its webhook.
   */
  appyPayMerchantTransactionId?: string | null;
  /**
   * AppyPay gateway transaction UUID.
   */
  appyPayTransactionId?: string | null;
  appyPayStatus?: ('Requested' | 'Pending' | 'Success' | 'Failed') | null;
  appyPayPaymentMethod?: string | null;
  appyPayResponseCode?: number | null;
  appyPayResponseMessage?: string | null;
  appyPayReferenceEntity?: string | null;
  appyPayReferenceNumber?: string | null;
  appyPayReferenceDueDate?: string | null;
  appyPayVerifiedAt?: string | null;
  /**
   * Automatic log of every status change -- who changed it and when. Not manually editable.
   */
  statusHistory?:
    | {
        status: string;
        changedAt: string;
        changedBy?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  market?: ('AO' | 'PT') | null;
  orderCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  channel: 'instagram';
  direction: 'inbound' | 'outbound';
  contactHandle: string;
  customerName?: string | null;
  body: string;
  instagramContextType?: string | null;
  instagramContextUrl?: string | null;
  instagramContextPermalink?: string | null;
  instagramContextMediaType?: string | null;
  replyToExternalId?: string | null;
  replyToText?: string | null;
  adminReadAt?: string | null;
  instagramSeenAt?: string | null;
  conversationStatus?: ('needs_reply' | 'waiting' | 'priority' | 'done') | null;
  status?: ('open' | 'auto_handled' | 'escalated' | 'resolved') | null;
  automationNote?: string | null;
  relatedOrder?: (number | null) | Order;
  relatedCustomer?: (number | null) | Customer;
  sentByAutomation?: boolean | null;
  externalId?: string | null;
  internalNote?: string | null;
  aiProcessingStatus?: ('queued' | 'processing' | 'draft_ready' | 'failed' | 'cancelled') | null;
  aiAttempts?: number | null;
  aiAvailableAt?: string | null;
  aiStartedAt?: string | null;
  aiCompletedAt?: string | null;
  aiCancelledAt?: string | null;
  aiLastError?: string | null;
  aiDraftStatus?: ('queued' | 'draft_ready' | 'approved' | 'dismissed' | 'failed') | null;
  aiDraft?: string | null;
  aiDraftConfidence?: number | null;
  aiDraftSourceRecordIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aiDraftReason?: string | null;
  aiMarket?: ('angola' | 'portugal') | null;
  aiIntent?: string | null;
  aiLanguage?: string | null;
  aiFacts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aiModel?: string | null;
  aiRequestId?: string | null;
  aiInputTokens?: number | null;
  aiOutputTokens?: number | null;
  aiTotalTokens?: number | null;
  aiEstimatedCostUsd?: number | null;
  aiRequiresHuman?: boolean | null;
  aiOutcome?: string | null;
  aiAutomationDecision?: string | null;
  aiBotPaused?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Commercial documents for accounting support. Not certified fiscal invoices.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  relatedOrder: number | Order;
  invoiceNumber: string;
  sequence: number;
  year: number;
  status: 'issued' | 'failed';
  market: 'AO' | 'PT';
  issuedAt: string;
  orderNumber: string;
  issuerName: string;
  issuerTaxId?: string | null;
  issuerAddress?: string | null;
  bankName?: string | null;
  accountHolder?: string | null;
  bankAccount?: string | null;
  swiftBic?: string | null;
  paymentInstructions?: string | null;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  customerTaxId?: string | null;
  customerAddress?: string | null;
  lines: {
    description: string;
    quantity: number;
    unitPrice: number;
    netAmount: number;
    taxAmount: number;
    grossAmount: number;
    id?: string | null;
  }[];
  currency: 'Kz' | 'EUR';
  vatRate: number;
  /**
   * Which VAT rate applied: PT region, or "flat" for Angola.
   */
  vatRegion?: ('mainland' | 'madeira' | 'azores' | 'flat') | null;
  taxNote?: string | null;
  subtotal: number;
  shipping: number;
  netTotal: number;
  taxTotal: number;
  total: number;
  paymentMethod?: string | null;
  paymentReference?: string | null;
  disclaimer: string;
  footer?: string | null;
  pdfFilename?: string | null;
  pdfData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * What shoppers type at checkout. Case-insensitive -- always stored/matched uppercase.
   */
  code: string;
  /**
   * Uncheck to disable without deleting (keeps redemption history on past orders intact).
   */
  active?: boolean | null;
  /**
   * Internal note (e.g. which campaign this is for) -- not shown to shoppers.
   */
  description?: string | null;
  type: 'percent' | 'fixed' | 'free_shipping';
  /**
   * 1-100.
   */
  percentOff?: number | null;
  /**
   * Leave blank to not offer this coupon in Angola.
   */
  fixedOffAOKz?: number | null;
  /**
   * Leave blank to not offer this coupon in Portugal.
   */
  fixedOffPTEur?: number | null;
  /**
   * Optional.
   */
  minOrderValueAOKz?: number | null;
  /**
   * Optional.
   */
  minOrderValuePTEur?: number | null;
  /**
   * Optional. Coupon is inactive before this date.
   */
  startDate?: string | null;
  /**
   * Optional. Coupon is inactive after this date.
   */
  endDate?: string | null;
  /**
   * Optional. Total redemptions allowed across every customer.
   */
  usageLimit?: number | null;
  /**
   * Incremented automatically whenever an order successfully uses this code.
   */
  usageCount?: number | null;
  /**
   * Optional. Caps how many times the same customer email can use this code.
   */
  maxRedemptionsPerEmail?: number | null;
  /**
   * Uncheck to make this code invalid for Angola orders.
   */
  availableAO?: boolean | null;
  /**
   * Uncheck to make this code invalid for Portugal orders.
   */
  availablePT?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'merch-tags';
        value: number | MerchTag;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'size-guides';
        value: number | SizeGuide;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  namePT?: T;
  nameEN?: T;
  slug?: T;
  category?: T;
  productType?: T;
  description?: T;
  descriptionPT?: T;
  descriptionEN?: T;
  sizeGuide?: T;
  fitNotePT?: T;
  fitNoteEN?: T;
  optionLabelPT?: T;
  optionLabelEN?: T;
  specifications?:
    | T
    | {
        labelPT?: T;
        labelEN?: T;
        valuePT?: T;
        valueEN?: T;
        id?: T;
      };
  returnEligible?: T;
  returnNotePT?: T;
  returnNoteEN?: T;
  tag?: T;
  images?:
    | T
    | {
        image?: T;
        color?: T;
        id?: T;
      };
  priceAOKz?: T;
  pricePTEur?: T;
  shippingWeightGrams?: T;
  saleAOKz?: T;
  salePTEur?: T;
  saleStartDate?: T;
  saleEndDate?: T;
  variants?:
    | T
    | {
        sku?: T;
        color?: T;
        size?: T;
        optionValueEN?: T;
        stockAO?: T;
        stockPT?: T;
        id?: T;
      };
  bundleComponents?:
    | T
    | {
        product?: T;
        variantId?: T;
        qty?: T;
        id?: T;
      };
  active?: T;
  availableAO?: T;
  availablePT?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  namePT?: T;
  nameEN?: T;
  introPT?: T;
  introEN?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch-tags_select".
 */
export interface MerchTagsSelect<T extends boolean = true> {
  labelPT?: T;
  labelEN?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  namePT?: T;
  nameEN?: T;
  hex?: T;
  hex2?: T;
  swatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-guides_select".
 */
export interface SizeGuidesSelect<T extends boolean = true> {
  name?: T;
  rows?:
    | T
    | {
        size?: T;
        bust?: T;
        waist?: T;
        hip?: T;
        length?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titlePT?: T;
  titleEN?: T;
  slug?: T;
  excerptPT?: T;
  excerptEN?: T;
  body?:
    | T
    | {
        kind?: T;
        headingPT?: T;
        headingEN?: T;
        textPT?: T;
        textEN?: T;
        id?: T;
      };
  seoTitlePT?: T;
  seoTitleEN?: T;
  seoDescriptionPT?: T;
  seoDescriptionEN?: T;
  status?: T;
  publishedAt?: T;
  availableAO?: T;
  availablePT?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  market?: T;
  status?: T;
  customerName?: T;
  customerFirstName?: T;
  customerLastName?: T;
  customerPhone?: T;
  customerEmail?: T;
  analyticsConsent?: T;
  metaFbp?: T;
  metaFbc?: T;
  metaEventSourceUrl?: T;
  lang?: T;
  address?: T;
  addressLine2?: T;
  postalCode?: T;
  deliveryRegion?: T;
  city?: T;
  country?: T;
  taxId?: T;
  notes?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        variantId?: T;
        size?: T;
        optionLabel?: T;
        optionValue?: T;
        color?: T;
        colorId?: T;
        productType?: T;
        inventoryComponents?: T;
        qty?: T;
        unitPrice?: T;
        regularUnitPrice?: T;
        saleDiscountAmount?: T;
        saleDiscountPercentage?: T;
        id?: T;
      };
  currency?: T;
  subtotal?: T;
  shippingCost?: T;
  couponCode?: T;
  discountAmount?: T;
  discountLabel?: T;
  total?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  inventoryReservationStatus?: T;
  inventoryReservationExpiresAt?: T;
  inventoryReservationReleasedAt?: T;
  deliveryMethod?: T;
  cttTrackingCode?: T;
  paymentReference?: T;
  appyPayMerchantTransactionId?: T;
  appyPayTransactionId?: T;
  appyPayStatus?: T;
  appyPayPaymentMethod?: T;
  appyPayResponseCode?: T;
  appyPayResponseMessage?: T;
  appyPayReferenceEntity?: T;
  appyPayReferenceNumber?: T;
  appyPayReferenceDueDate?: T;
  appyPayVerifiedAt?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        changedBy?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  market?: T;
  orderCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  channel?: T;
  direction?: T;
  contactHandle?: T;
  customerName?: T;
  body?: T;
  instagramContextType?: T;
  instagramContextUrl?: T;
  instagramContextPermalink?: T;
  instagramContextMediaType?: T;
  replyToExternalId?: T;
  replyToText?: T;
  adminReadAt?: T;
  instagramSeenAt?: T;
  conversationStatus?: T;
  status?: T;
  automationNote?: T;
  relatedOrder?: T;
  relatedCustomer?: T;
  sentByAutomation?: T;
  externalId?: T;
  internalNote?: T;
  aiProcessingStatus?: T;
  aiAttempts?: T;
  aiAvailableAt?: T;
  aiStartedAt?: T;
  aiCompletedAt?: T;
  aiCancelledAt?: T;
  aiLastError?: T;
  aiDraftStatus?: T;
  aiDraft?: T;
  aiDraftConfidence?: T;
  aiDraftSourceRecordIds?: T;
  aiDraftReason?: T;
  aiMarket?: T;
  aiIntent?: T;
  aiLanguage?: T;
  aiFacts?: T;
  aiModel?: T;
  aiRequestId?: T;
  aiInputTokens?: T;
  aiOutputTokens?: T;
  aiTotalTokens?: T;
  aiEstimatedCostUsd?: T;
  aiRequiresHuman?: T;
  aiOutcome?: T;
  aiAutomationDecision?: T;
  aiBotPaused?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  relatedOrder?: T;
  invoiceNumber?: T;
  sequence?: T;
  year?: T;
  status?: T;
  market?: T;
  issuedAt?: T;
  orderNumber?: T;
  issuerName?: T;
  issuerTaxId?: T;
  issuerAddress?: T;
  bankName?: T;
  accountHolder?: T;
  bankAccount?: T;
  swiftBic?: T;
  paymentInstructions?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerTaxId?: T;
  customerAddress?: T;
  lines?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        netAmount?: T;
        taxAmount?: T;
        grossAmount?: T;
        id?: T;
      };
  currency?: T;
  vatRate?: T;
  vatRegion?: T;
  taxNote?: T;
  subtotal?: T;
  shipping?: T;
  netTotal?: T;
  taxTotal?: T;
  total?: T;
  paymentMethod?: T;
  paymentReference?: T;
  disclaimer?: T;
  footer?: T;
  pdfFilename?: T;
  pdfData?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  active?: T;
  description?: T;
  type?: T;
  percentOff?: T;
  fixedOffAOKz?: T;
  fixedOffPTEur?: T;
  minOrderValueAOKz?: T;
  minOrderValuePTEur?: T;
  startDate?: T;
  endDate?: T;
  usageLimit?: T;
  usageCount?: T;
  maxRedemptionsPerEmail?: T;
  availableAO?: T;
  availablePT?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings".
 */
export interface MarketSetting {
  id: number;
  /**
   * Turn ON only after the AppyPay application and webhook are operational. Stripe/PayPal for Angola are unaffected because they use the separate EUR settlement path.
   */
  angolaPaymentLive?: boolean | null;
  /**
   * Digits only or +country code. Used by both markets unless a market-specific number is set below.
   */
  manualWhatsappNumber?: string | null;
  angolaWhatsappNumber?: string | null;
  portugalWhatsappNumber?: string | null;
  /**
   * Optional. Placeholders: {orderNumber}, {market}, {customerName}, {total}, {delivery}, {items}.
   */
  manualWhatsappMessagePT?: string | null;
  /**
   * Optional English template using the same placeholders.
   */
  manualWhatsappMessageEN?: string | null;
  /**
   * Shown at checkout while angolaPaymentLive is off. Explain that the order will be coordinated through WhatsApp.
   */
  angolaBankTransferInstructionsPT?: string | null;
  /**
   * English translation of the field above.
   */
  angolaBankTransferInstructionsEN?: string | null;
  angolaPaymentMethods?: ('multicaixa_express' | 'stripe' | 'paypal')[] | null;
  angolaDeliveryMethods?: 'courier_ao'[] | null;
  /**
   * Placeholder local-courier prices. Edit the Kz value for any municipality; keep all 16 keys.
   */
  angolaMunicipalityPrices:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Applied to the merchandise total after discounts.
   */
  angolaFreeShippingThreshold: number;
  /**
   * Keep OFF until the Portuguese legal entity, invoicing process, and payment-provider accounts are approved. Turning this on re-enables PT checkout.
   */
  portugalPaymentsEnabled?: boolean | null;
  /**
   * Shown at checkout while portugalPaymentsEnabled is off.
   */
  portugalManualCheckoutInstructionsPT?: string | null;
  /**
   * English translation of the field above.
   */
  portugalManualCheckoutInstructionsEN?: string | null;
  portugalPaymentMethods?: ('paypal' | 'stripe' | 'mbway')[] | null;
  portugalDeliveryMethods?: ('ctt' | 'courier_pt')[] | null;
  /**
   * Customer charge for the untracked option below the free-delivery threshold.
   */
  portugalStandardShippingPrice: number;
  /**
   * Customer charge for tracked CTT delivery below the free-delivery threshold.
   */
  portugalTrackedShippingPrice: number;
  /**
   * Applied to the merchandise total after coupons and other discounts.
   */
  portugalFreeShippingThreshold: number;
  portugalStandardWeightLimitGrams: number;
  portugalHeavyMainlandShippingPrice: number;
  portugalHeavyIslandsShippingPrice: number;
  /**
   * Client-provided legal copy (JOS-64, added 2026-07-23). Angola’s policy has separate business/legal terms from Portugal’s, so it is a separate field rather than a shared translation.
   */
  angolaReturnsPolicyTextPT?: string | null;
  /**
   * English translation of the field above (JOS-64, added 2026-07-24), so the policy is bilingual like the rest of the storefront.
   */
  angolaReturnsPolicyTextEN?: string | null;
  /**
   * Client-provided legal copy (JOS-64, added 2026-07-23). 14-day EU distance-selling withdrawal window.
   */
  portugalReturnsPolicyTextPT?: string | null;
  /**
   * English translation of the field above (JOS-64, added 2026-07-24), so the policy is bilingual like the rest of the storefront.
   */
  portugalReturnsPolicyTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  businessHoursTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  businessHoursTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  angolaShippingTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  angolaShippingTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  portugalShippingTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  portugalShippingTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  internationalShippingTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  internationalShippingTextEN?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phase 1 commercial documents for accounting support. These settings are snapshotted onto each invoice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-settings".
 */
export interface InvoiceSetting {
  id: number;
  phaseOneDisclaimerPT: string;
  phaseOneDisclaimerEN: string;
  invoicingEnabledAO?: boolean | null;
  issuerNameAO?: string | null;
  issuerTaxIdAO?: string | null;
  issuerAddressAO?: string | null;
  bankNameAO?: string | null;
  accountHolderAO?: string | null;
  bankAccountAO?: string | null;
  swiftBicAO?: string | null;
  paymentInstructionsAO?: string | null;
  /**
   * The paid total never changes. This rate extracts the VAT portion already included in the price. Angola VAT is a flat 14% nationwide.
   */
  vatRateAO?: number | null;
  /**
   * Optional note supplied by the accountant.
   */
  taxNoteAO?: string | null;
  invoicePrefixAO?: string | null;
  invoiceFooterAO?: string | null;
  invoicingEnabledPT?: boolean | null;
  issuerNamePT?: string | null;
  issuerTaxIdPT?: string | null;
  issuerAddressPT?: string | null;
  bankNamePT?: string | null;
  accountHolderPT?: string | null;
  bankAccountPT?: string | null;
  swiftBicPT?: string | null;
  paymentInstructionsPT?: string | null;
  /**
   * Applied to PT orders whose postal code classifies as mainland.
   */
  vatRatePortugalMainland?: number | null;
  /**
   * Applied to PT orders whose postal code classifies as Madeira.
   */
  vatRatePortugalMadeira?: number | null;
  /**
   * Applied to PT orders whose postal code classifies as Azores.
   */
  vatRatePortugalAzores?: number | null;
  /**
   * Optional note supplied by the accountant.
   */
  taxNotePT?: string | null;
  invoicePrefixPT?: string | null;
  invoiceFooterPT?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Privacy Policy and Terms & Conditions shown on the storefront. The seeded text is an AI-drafted generic template -- have it reviewed by a lawyer before treating it as final.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-content".
 */
export interface LegalContent {
  id: number;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  privacyPolicyTextPT?: string | null;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  privacyPolicyTextEN?: string | null;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  termsTextPT?: string | null;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  termsTextEN?: string | null;
  /**
   * Added 2026-08-01 for the Meta App Dashboard "Data Deletion Instructions URL" requirement (needed to publish the WhatsApp/Instagram messaging app). AI-drafted -- needs legal review before final.
   */
  dataDeletionTextPT?: string | null;
  /**
   * Added 2026-08-01 for the Meta App Dashboard "Data Deletion Instructions URL" requirement (needed to publish the WhatsApp/Instagram messaging app). AI-drafted -- needs legal review before final.
   */
  dataDeletionTextEN?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable content for the storefront home page's hero banner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  /**
   * Small label above the headline, e.g. "Coleção SS26".
   */
  heroEyebrowPT?: string | null;
  heroEyebrowEN?: string | null;
  heroHeadlinePT?: string | null;
  heroHeadlineEN?: string | null;
  heroSubtitlePT?: string | null;
  heroSubtitleEN?: string | null;
  heroCtaLabelPT?: string | null;
  heroCtaLabelEN?: string | null;
  /**
   * Where the hero button sends shoppers.
   */
  heroCtaType?: ('all' | 'category' | 'tag') | null;
  /**
   * Only used when link type is "One category".
   */
  heroCtaCategorySlug?: string | null;
  /**
   * Only used when link type is "Merchandising tag". Pick a tag on the right.
   */
  heroCtaTagSlug?: string | null;
  /**
   * Desktop composition. Replaces the decorative placeholder graphic when set.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional mobile composition. The desktop image is used as a safe fallback when this is empty.
   */
  heroImageMobile?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Which categories appear on the storefront home page, and in what order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-categories".
 */
export interface HomeCategory {
  id: number;
  /**
   * Which categories appear in the homepage category row, and in what order. Leave empty to show every category (today's behaviour).
   */
  homepageCategorySlugs?:
    | {
        /**
         * Picked from the real category list in Settings -- see Settings.tsx.
         */
        slug: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tag-driven product shelves shown on the storefront home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-collections".
 */
export interface HomeCollection {
  id: number;
  /**
   * Each row is one product shelf on the homepage, driven by a merchandising tag (e.g. "New", "Bestseller", "SS26"). Leave empty to keep the previous fixed New Arrivals / Featured sections.
   */
  collections?:
    | {
        /**
         * Picked from the real merch tag list in Settings.
         */
        tagSlug: string;
        titlePT: string;
        titleEN: string;
        /**
         * Maximum products shown in this shelf.
         */
        itemLimit?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pick which of the ~12 most recent Instagram posts is shown as the large, highlighted tile in the homepage "Instagram feed" section. Leave empty to show all recent posts the same size. Managed from the storefront admin's Settings > Instagram feed tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-spotlight".
 */
export interface InstagramSpotlight {
  id: number;
  /**
   * e.g. https://www.instagram.com/p/AbCdEfG/ -- must still be one of the ~12 most recent posts, or nothing will be highlighted.
   */
  highlightedPermalink?: string | null;
  /**
   * Products linked to individual Instagram posts. Managed from Storefront Admin > Settings > Instagram feed.
   */
  productTags?:
    | {
        /**
         * Stable Instagram identifier. The permalink remains as a fallback when older entries have no media ID.
         */
        mediaId?: string | null;
        permalink: string;
        products?: (number | Product)[] | null;
        /**
         * Storefront-admin managed map of product ID to the colour visible in the Instagram post.
         */
        variantSelections?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls Instagram AI drafts and the guarded hybrid auto-reply mode.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-messaging-settings".
 */
export interface AiMessagingSetting {
  id: number;
  assistantEnabled?: boolean | null;
  /**
   * Immediately stops new AI processing and automatic replies. Existing messages remain available to staff.
   */
  emergencyStop?: boolean | null;
  operatingMode: 'approval' | 'hybrid';
  autoReplyIntents?:
    | (
        | 'greeting'
        | 'product_availability'
        | 'product_price'
        | 'product_sizing'
        | 'delivery'
        | 'payment'
        | 'coupon'
        | 'return_policy'
      )[]
    | null;
  autoReplyMarketClarification?: boolean | null;
  autoReplyProductClarification?: boolean | null;
  /**
   * 0.92 means 92%. Lower values automate more replies but increase risk.
   */
  confidenceThreshold: number;
  /**
   * Lets consecutive customer messages arrive before the assistant responds.
   */
  replyDelaySeconds: number;
  maxAutoRepliesPerConversation: number;
  maxAutoRepliesPerHour: number;
  /**
   * New AI processing pauses when the estimated application spend reaches this amount.
   */
  monthlyBudgetUsd: number;
  outOfStockRecoveryEnabled?: boolean | null;
  outOfStockAllowOtherColours?: boolean | null;
  outOfStockAllowOtherSizes?: boolean | null;
  outOfStockMaxAlternatives: number;
  /**
   * Related products outside this difference from the requested product are excluded.
   */
  outOfStockPriceTolerancePercent: number;
  outOfStockCategoryWeight: number;
  outOfStockTagWeight: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage SEO, About, FAQ and standalone size-guide page copy. Day-to-day editing is available in the custom storefront admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefront-content".
 */
export interface StorefrontContent {
  id: number;
  /**
   * Optional. Leave blank until the official profile exists; the storefront only publishes a valid profile URL.
   */
  tiktokUrl?: string | null;
  homeSeoTitleAngolaPT?: string | null;
  homeSeoTitleAngolaEN?: string | null;
  homeSeoDescriptionAngolaPT?: string | null;
  homeSeoDescriptionAngolaEN?: string | null;
  homeSeoTitlePortugalPT?: string | null;
  homeSeoTitlePortugalEN?: string | null;
  homeSeoDescriptionPortugalPT?: string | null;
  homeSeoDescriptionPortugalEN?: string | null;
  aboutEyebrowPT?: string | null;
  aboutEyebrowEN?: string | null;
  aboutTitlePT?: string | null;
  aboutTitleEN?: string | null;
  aboutIntroPT?: string | null;
  aboutIntroEN?: string | null;
  aboutStoryTitlePT?: string | null;
  aboutStoryTitleEN?: string | null;
  aboutStoryBodyPT?: string | null;
  aboutStoryBodyEN?: string | null;
  aboutValuesTitlePT?: string | null;
  aboutValuesTitleEN?: string | null;
  aboutValues?:
    | {
        enabled?: boolean | null;
        titlePT: string;
        titleEN: string;
        bodyPT: string;
        bodyEN: string;
        id?: string | null;
      }[]
    | null;
  aboutPresenceTitlePT?: string | null;
  aboutPresenceTitleEN?: string | null;
  aboutAngolaTitlePT?: string | null;
  aboutAngolaTitleEN?: string | null;
  aboutAngolaBodyPT?: string | null;
  aboutAngolaBodyEN?: string | null;
  aboutPortugalTitlePT?: string | null;
  aboutPortugalTitleEN?: string | null;
  aboutPortugalBodyPT?: string | null;
  aboutPortugalBodyEN?: string | null;
  aboutCtaLabelPT?: string | null;
  aboutCtaLabelEN?: string | null;
  aboutSeoTitlePT?: string | null;
  aboutSeoTitleEN?: string | null;
  aboutSeoDescriptionPT?: string | null;
  aboutSeoDescriptionEN?: string | null;
  faqTitlePT?: string | null;
  faqTitleEN?: string | null;
  faqIntroPT?: string | null;
  faqIntroEN?: string | null;
  faqSupportPromptPT?: string | null;
  faqSupportPromptEN?: string | null;
  faqSupportLabelPT?: string | null;
  faqSupportLabelEN?: string | null;
  faqSeoTitlePT?: string | null;
  faqSeoTitleEN?: string | null;
  faqSeoDescriptionPT?: string | null;
  faqSeoDescriptionEN?: string | null;
  faqEntries?:
    | {
        enabled?: boolean | null;
        questionPT: string;
        questionEN: string;
        answerPT: string;
        answerEN: string;
        answerPTPT?: string | null;
        answerENPT?: string | null;
        /**
         * Optional internal path, e.g. /ajuda#devolucoes.
         */
        linkPath?: string | null;
        linkLabelPT?: string | null;
        linkLabelEN?: string | null;
        id?: string | null;
      }[]
    | null;
  sizeGuideTitlePT?: string | null;
  sizeGuideTitleEN?: string | null;
  sizeGuideIntroPT?: string | null;
  sizeGuideIntroEN?: string | null;
  sizeGuideHowToTitlePT?: string | null;
  sizeGuideHowToTitleEN?: string | null;
  sizeGuideBustPT?: string | null;
  sizeGuideBustEN?: string | null;
  sizeGuideWaistPT?: string | null;
  sizeGuideWaistEN?: string | null;
  sizeGuideHipPT?: string | null;
  sizeGuideHipEN?: string | null;
  sizeGuideLengthPT?: string | null;
  sizeGuideLengthEN?: string | null;
  sizeGuideClosingPT?: string | null;
  sizeGuideClosingEN?: string | null;
  sizeGuideSupportLabelPT?: string | null;
  sizeGuideSupportLabelEN?: string | null;
  sizeGuideCatalogLabelPT?: string | null;
  sizeGuideCatalogLabelEN?: string | null;
  sizeGuideSeoTitlePT?: string | null;
  sizeGuideSeoTitleEN?: string | null;
  sizeGuideSeoDescriptionPT?: string | null;
  sizeGuideSeoDescriptionEN?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings_select".
 */
export interface MarketSettingsSelect<T extends boolean = true> {
  angolaPaymentLive?: T;
  manualWhatsappNumber?: T;
  angolaWhatsappNumber?: T;
  portugalWhatsappNumber?: T;
  manualWhatsappMessagePT?: T;
  manualWhatsappMessageEN?: T;
  angolaBankTransferInstructionsPT?: T;
  angolaBankTransferInstructionsEN?: T;
  angolaPaymentMethods?: T;
  angolaDeliveryMethods?: T;
  angolaMunicipalityPrices?: T;
  angolaFreeShippingThreshold?: T;
  portugalPaymentsEnabled?: T;
  portugalManualCheckoutInstructionsPT?: T;
  portugalManualCheckoutInstructionsEN?: T;
  portugalPaymentMethods?: T;
  portugalDeliveryMethods?: T;
  portugalStandardShippingPrice?: T;
  portugalTrackedShippingPrice?: T;
  portugalFreeShippingThreshold?: T;
  portugalStandardWeightLimitGrams?: T;
  portugalHeavyMainlandShippingPrice?: T;
  portugalHeavyIslandsShippingPrice?: T;
  angolaReturnsPolicyTextPT?: T;
  angolaReturnsPolicyTextEN?: T;
  portugalReturnsPolicyTextPT?: T;
  portugalReturnsPolicyTextEN?: T;
  businessHoursTextPT?: T;
  businessHoursTextEN?: T;
  angolaShippingTextPT?: T;
  angolaShippingTextEN?: T;
  portugalShippingTextPT?: T;
  portugalShippingTextEN?: T;
  internationalShippingTextPT?: T;
  internationalShippingTextEN?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-settings_select".
 */
export interface InvoiceSettingsSelect<T extends boolean = true> {
  phaseOneDisclaimerPT?: T;
  phaseOneDisclaimerEN?: T;
  invoicingEnabledAO?: T;
  issuerNameAO?: T;
  issuerTaxIdAO?: T;
  issuerAddressAO?: T;
  bankNameAO?: T;
  accountHolderAO?: T;
  bankAccountAO?: T;
  swiftBicAO?: T;
  paymentInstructionsAO?: T;
  vatRateAO?: T;
  taxNoteAO?: T;
  invoicePrefixAO?: T;
  invoiceFooterAO?: T;
  invoicingEnabledPT?: T;
  issuerNamePT?: T;
  issuerTaxIdPT?: T;
  issuerAddressPT?: T;
  bankNamePT?: T;
  accountHolderPT?: T;
  bankAccountPT?: T;
  swiftBicPT?: T;
  paymentInstructionsPT?: T;
  vatRatePortugalMainland?: T;
  vatRatePortugalMadeira?: T;
  vatRatePortugalAzores?: T;
  taxNotePT?: T;
  invoicePrefixPT?: T;
  invoiceFooterPT?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-content_select".
 */
export interface LegalContentSelect<T extends boolean = true> {
  privacyPolicyTextPT?: T;
  privacyPolicyTextEN?: T;
  termsTextPT?: T;
  termsTextEN?: T;
  dataDeletionTextPT?: T;
  dataDeletionTextEN?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  heroEyebrowPT?: T;
  heroEyebrowEN?: T;
  heroHeadlinePT?: T;
  heroHeadlineEN?: T;
  heroSubtitlePT?: T;
  heroSubtitleEN?: T;
  heroCtaLabelPT?: T;
  heroCtaLabelEN?: T;
  heroCtaType?: T;
  heroCtaCategorySlug?: T;
  heroCtaTagSlug?: T;
  heroImage?: T;
  heroImageMobile?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-categories_select".
 */
export interface HomeCategoriesSelect<T extends boolean = true> {
  homepageCategorySlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-collections_select".
 */
export interface HomeCollectionsSelect<T extends boolean = true> {
  collections?:
    | T
    | {
        tagSlug?: T;
        titlePT?: T;
        titleEN?: T;
        itemLimit?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-spotlight_select".
 */
export interface InstagramSpotlightSelect<T extends boolean = true> {
  highlightedPermalink?: T;
  productTags?:
    | T
    | {
        mediaId?: T;
        permalink?: T;
        products?: T;
        variantSelections?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-messaging-settings_select".
 */
export interface AiMessagingSettingsSelect<T extends boolean = true> {
  assistantEnabled?: T;
  emergencyStop?: T;
  operatingMode?: T;
  autoReplyIntents?: T;
  autoReplyMarketClarification?: T;
  autoReplyProductClarification?: T;
  confidenceThreshold?: T;
  replyDelaySeconds?: T;
  maxAutoRepliesPerConversation?: T;
  maxAutoRepliesPerHour?: T;
  monthlyBudgetUsd?: T;
  outOfStockRecoveryEnabled?: T;
  outOfStockAllowOtherColours?: T;
  outOfStockAllowOtherSizes?: T;
  outOfStockMaxAlternatives?: T;
  outOfStockPriceTolerancePercent?: T;
  outOfStockCategoryWeight?: T;
  outOfStockTagWeight?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefront-content_select".
 */
export interface StorefrontContentSelect<T extends boolean = true> {
  tiktokUrl?: T;
  homeSeoTitleAngolaPT?: T;
  homeSeoTitleAngolaEN?: T;
  homeSeoDescriptionAngolaPT?: T;
  homeSeoDescriptionAngolaEN?: T;
  homeSeoTitlePortugalPT?: T;
  homeSeoTitlePortugalEN?: T;
  homeSeoDescriptionPortugalPT?: T;
  homeSeoDescriptionPortugalEN?: T;
  aboutEyebrowPT?: T;
  aboutEyebrowEN?: T;
  aboutTitlePT?: T;
  aboutTitleEN?: T;
  aboutIntroPT?: T;
  aboutIntroEN?: T;
  aboutStoryTitlePT?: T;
  aboutStoryTitleEN?: T;
  aboutStoryBodyPT?: T;
  aboutStoryBodyEN?: T;
  aboutValuesTitlePT?: T;
  aboutValuesTitleEN?: T;
  aboutValues?:
    | T
    | {
        enabled?: T;
        titlePT?: T;
        titleEN?: T;
        bodyPT?: T;
        bodyEN?: T;
        id?: T;
      };
  aboutPresenceTitlePT?: T;
  aboutPresenceTitleEN?: T;
  aboutAngolaTitlePT?: T;
  aboutAngolaTitleEN?: T;
  aboutAngolaBodyPT?: T;
  aboutAngolaBodyEN?: T;
  aboutPortugalTitlePT?: T;
  aboutPortugalTitleEN?: T;
  aboutPortugalBodyPT?: T;
  aboutPortugalBodyEN?: T;
  aboutCtaLabelPT?: T;
  aboutCtaLabelEN?: T;
  aboutSeoTitlePT?: T;
  aboutSeoTitleEN?: T;
  aboutSeoDescriptionPT?: T;
  aboutSeoDescriptionEN?: T;
  faqTitlePT?: T;
  faqTitleEN?: T;
  faqIntroPT?: T;
  faqIntroEN?: T;
  faqSupportPromptPT?: T;
  faqSupportPromptEN?: T;
  faqSupportLabelPT?: T;
  faqSupportLabelEN?: T;
  faqSeoTitlePT?: T;
  faqSeoTitleEN?: T;
  faqSeoDescriptionPT?: T;
  faqSeoDescriptionEN?: T;
  faqEntries?:
    | T
    | {
        enabled?: T;
        questionPT?: T;
        questionEN?: T;
        answerPT?: T;
        answerEN?: T;
        answerPTPT?: T;
        answerENPT?: T;
        linkPath?: T;
        linkLabelPT?: T;
        linkLabelEN?: T;
        id?: T;
      };
  sizeGuideTitlePT?: T;
  sizeGuideTitleEN?: T;
  sizeGuideIntroPT?: T;
  sizeGuideIntroEN?: T;
  sizeGuideHowToTitlePT?: T;
  sizeGuideHowToTitleEN?: T;
  sizeGuideBustPT?: T;
  sizeGuideBustEN?: T;
  sizeGuideWaistPT?: T;
  sizeGuideWaistEN?: T;
  sizeGuideHipPT?: T;
  sizeGuideHipEN?: T;
  sizeGuideLengthPT?: T;
  sizeGuideLengthEN?: T;
  sizeGuideClosingPT?: T;
  sizeGuideClosingEN?: T;
  sizeGuideSupportLabelPT?: T;
  sizeGuideSupportLabelEN?: T;
  sizeGuideCatalogLabelPT?: T;
  sizeGuideCatalogLabelEN?: T;
  sizeGuideSeoTitlePT?: T;
  sizeGuideSeoTitleEN?: T;
  sizeGuideSeoDescriptionPT?: T;
  sizeGuideSeoDescriptionEN?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}