/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    'merch-tags': MerchTag;
    colors: Color;
    'size-guides': SizeGuide;
    orders: Order;
    customers: Customer;
    messages: Message;
    invoices: Invoice;
    coupons: Coupon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'merch-tags': MerchTagsSelect<false> | MerchTagsSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    'size-guides': SizeGuidesSelect<false> | SizeGuidesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'market-settings': MarketSetting;
    'invoice-settings': InvoiceSetting;
    'legal-content': LegalContent;
    'home-content': HomeContent;
  };
  globalsSelect: {
    'market-settings': MarketSettingsSelect<false> | MarketSettingsSelect<true>;
    'invoice-settings': InvoiceSettingsSelect<false> | InvoiceSettingsSelect<true>;
    'legal-content': LegalContentSelect<false> | LegalContentSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Internal/default product name (kept aligned with the Portuguese name).
   */
  name: string;
  namePT?: string | null;
  nameEN?: string | null;
  /**
   * Auto-generated from the product name -- not editable (2026-07-25 admin request). See generateProductSlug in src/lib/productSlug.ts.
   */
  slug: string;
  category: number | Category;
  /**
   * Legacy/default description. New storefront editing uses the language-specific fields below.
   */
  description?: string | null;
  descriptionPT?: string | null;
  descriptionEN?: string | null;
  /**
   * Optional. Shared measurement chart shown in the product page size-guide modal.
   */
  sizeGuide?: (number | null) | SizeGuide;
  /**
   * Optional short per-product advice shown under the size chart, e.g. "Veste pequeno, recomendamos um tamanho acima."
   */
  fitNotePT?: string | null;
  fitNoteEN?: string | null;
  /**
   * Optional merchandising badge(s) shown on the product card.
   */
  tag?: (number | MerchTag)[] | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  priceAOKz: number;
  pricePTEur: number;
  /**
   * Used to calculate Portugal parcel shipping. Include normal product packaging.
   */
  shippingWeightGrams: number;
  /**
   * Optional. Replaces the regular Angola price while set and within the sale window (if any).
   */
  saleAOKz?: number | null;
  /**
   * Optional. Replaces the regular Portugal price while set and within the sale window (if any).
   */
  salePTEur?: number | null;
  /**
   * Optional. Leave blank for the sale to be active immediately.
   */
  saleStartDate?: string | null;
  /**
   * Optional. Leave blank for the sale to run indefinitely.
   */
  saleEndDate?: string | null;
  /**
   * One row per colour + size combination, with per-market stock.
   */
  variants: {
    color: number | Color;
    size: 'XS' | 'S' | 'M' | 'L' | 'XL';
    stockAO: number;
    stockPT: number;
    id?: string | null;
  }[];
  /**
   * Unpublish to hide from the storefront without deleting it.
   */
  active?: boolean | null;
  /**
   * Uncheck to hide this product from the Angola storefront entirely.
   */
  availableAO?: boolean | null;
  /**
   * Uncheck to hide this product from the Portugal storefront entirely.
   */
  availablePT?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  namePT: string;
  /**
   * Shown when the shopper switches the storefront to English. Falls back to the Portuguese name if empty.
   */
  nameEN?: string | null;
  /**
   * Auto-generated from the Portuguese name; used in storefront URLs (/catalogo?cat=...). Not editable.
   */
  slug?: string | null;
  /**
   * Shown on the home page's category tiles. Optional -- falls back to a decorative placeholder when unset.
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-guides".
 */
export interface SizeGuide {
  id: number;
  /**
   * Internal name, e.g. "Vestidos — padrão". Shoppers never see this.
   */
  name: string;
  /**
   * One row per size. All measurements in centimetres; leave blank any that do not apply to this garment type.
   */
  rows: {
    size: 'XS' | 'S' | 'M' | 'L' | 'XL';
    bust?: number | null;
    waist?: number | null;
    hip?: number | null;
    length?: number | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch-tags".
 */
export interface MerchTag {
  id: number;
  /**
   * Badge text shown on product cards, e.g. "Novidade".
   */
  labelPT: string;
  /**
   * Shown on the English storefront. Falls back to the Portuguese label if empty.
   */
  labelEN?: string | null;
  /**
   * Auto-generated from the Portuguese label; usable as a storefront "collection" link (/catalogo?tag=...). Not editable.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  /**
   * Display name, e.g. "Verde Oliva".
   */
  namePT: string;
  /**
   * Shown when the shopper switches the storefront to English. Falls back to the Portuguese name if empty.
   */
  nameEN?: string | null;
  /**
   * Solid-colour swatch, e.g. #7A8B5C. Leave empty for patterned fabrics and upload a swatch image instead.
   */
  hex?: string | null;
  /**
   * Optional. Set this to create a two-tone combination colour -- the swatch renders as a split circle.
   */
  hex2?: string | null;
  /**
   * Optional. For patterns/multicolour fabrics where a single hex value is not representative. Takes precedence over the hex value.
   */
  swatch?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  market: 'AO' | 'PT';
  status?: ('new' | 'payment_review' | 'processing' | 'shipped' | 'delivered' | 'cancelled') | null;
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  analyticsConsent?: boolean | null;
  metaFbp?: string | null;
  metaFbc?: string | null;
  metaEventSourceUrl?: string | null;
  /**
   * Storefront language the customer had selected at checkout -- determines the language of the order-confirmation email.
   */
  lang?: ('pt' | 'en') | null;
  address: string;
  /**
   * Optional PT address line -- not collected for Angola orders.
   */
  addressLine2?: string | null;
  /**
   * CTT format 0000-000 -- validated client-side on the PT storefront, not collected for Angola.
   */
  postalCode?: string | null;
  /**
   * Classified automatically from the Portuguese postal code when the order is created.
   */
  deliveryRegion?: ('mainland' | 'madeira' | 'azores') | null;
  city: string;
  country: string;
  /**
   * Customer tax number, optional -- snapshotted onto the internal commercial invoice for accounting review.
   */
  taxId?: string | null;
  notes?: string | null;
  items: {
    product: number | Product;
    productName: string;
    size: string;
    color?: string | null;
    colorId?: string | null;
    qty: number;
    unitPrice: number;
    id?: string | null;
  }[];
  currency: 'Kz' | 'EUR';
  subtotal: number;
  shippingCost: number;
  /**
   * Snapshot of the coupon code used, if any.
   */
  couponCode?: string | null;
  /**
   * Amount deducted by the coupon, in the order currency.
   */
  discountAmount?: number | null;
  /**
   * Human-readable label shown on the invoice/admin, e.g. "SS26 (10% off)".
   */
  discountLabel?: string | null;
  total: number;
  paymentMethod: 'paypal' | 'stripe' | 'mbway' | 'multicaixa_express' | 'bank_transfer_ao' | 'sweg_appypay';
  paymentStatus?: ('pending' | 'awaiting_manual_review' | 'paid' | 'failed') | null;
  inventoryReservationStatus?: ('none' | 'active' | 'committed' | 'released') | null;
  inventoryReservationExpiresAt?: string | null;
  inventoryReservationReleasedAt?: string | null;
  deliveryMethod: 'ctt' | 'courier_pt' | 'courier_ao' | 'manual_ao';
  /**
   * For CTT Registered orders, enter the code from the CTT receipt or shipping portal. It becomes visible in the customer order lookup.
   */
  cttTrackingCode?: string | null;
  /**
   * Provider transaction ID (Stripe, PayPal or AppyPay) -- set automatically for admin troubleshooting.
   */
  paymentReference?: string | null;
  /**
   * Our <=15 character alphanumeric transaction ID sent to the AppyPay widget and echoed by its webhook.
   */
  appyPayMerchantTransactionId?: string | null;
  /**
   * AppyPay gateway transaction UUID.
   */
  appyPayTransactionId?: string | null;
  appyPayStatus?: ('Requested' | 'Pending' | 'Success' | 'Failed') | null;
  appyPayPaymentMethod?: string | null;
  appyPayResponseCode?: number | null;
  appyPayResponseMessage?: string | null;
  appyPayReferenceEntity?: string | null;
  appyPayReferenceNumber?: string | null;
  appyPayReferenceDueDate?: string | null;
  appyPayVerifiedAt?: string | null;
  /**
   * Automatic log of every status change -- who changed it and when. Not manually editable.
   */
  statusHistory?:
    | {
        status: string;
        changedAt: string;
        changedBy?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  market?: ('AO' | 'PT') | null;
  orderCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  channel: 'whatsapp' | 'instagram';
  direction: 'inbound' | 'outbound';
  contactHandle: string;
  customerName?: string | null;
  body: string;
  status?: ('open' | 'auto_handled' | 'escalated' | 'resolved') | null;
  automationNote?: string | null;
  relatedOrder?: (number | null) | Order;
  relatedCustomer?: (number | null) | Customer;
  sentByAutomation?: boolean | null;
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Commercial documents for accounting support. Not certified fiscal invoices.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  relatedOrder: number | Order;
  invoiceNumber: string;
  sequence: number;
  year: number;
  status: 'issued' | 'failed';
  market: 'AO' | 'PT';
  issuedAt: string;
  orderNumber: string;
  issuerName: string;
  issuerTaxId?: string | null;
  issuerAddress?: string | null;
  bankName?: string | null;
  accountHolder?: string | null;
  bankAccount?: string | null;
  swiftBic?: string | null;
  paymentInstructions?: string | null;
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  customerTaxId?: string | null;
  customerAddress?: string | null;
  lines: {
    description: string;
    quantity: number;
    unitPrice: number;
    netAmount: number;
    taxAmount: number;
    grossAmount: number;
    id?: string | null;
  }[];
  currency: 'Kz' | 'EUR';
  vatRate: number;
  taxNote?: string | null;
  subtotal: number;
  shipping: number;
  netTotal: number;
  taxTotal: number;
  total: number;
  paymentMethod?: string | null;
  paymentReference?: string | null;
  disclaimer: string;
  footer?: string | null;
  pdfFilename?: string | null;
  pdfData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * What shoppers type at checkout. Case-insensitive -- always stored/matched uppercase.
   */
  code: string;
  /**
   * Uncheck to disable without deleting (keeps redemption history on past orders intact).
   */
  active?: boolean | null;
  /**
   * Internal note (e.g. which campaign this is for) -- not shown to shoppers.
   */
  description?: string | null;
  type: 'percent' | 'fixed' | 'free_shipping';
  /**
   * 1-100.
   */
  percentOff?: number | null;
  /**
   * Leave blank to not offer this coupon in Angola.
   */
  fixedOffAOKz?: number | null;
  /**
   * Leave blank to not offer this coupon in Portugal.
   */
  fixedOffPTEur?: number | null;
  /**
   * Optional.
   */
  minOrderValueAOKz?: number | null;
  /**
   * Optional.
   */
  minOrderValuePTEur?: number | null;
  /**
   * Optional. Coupon is inactive before this date.
   */
  startDate?: string | null;
  /**
   * Optional. Coupon is inactive after this date.
   */
  endDate?: string | null;
  /**
   * Optional. Total redemptions allowed across every customer.
   */
  usageLimit?: number | null;
  /**
   * Incremented automatically whenever an order successfully uses this code.
   */
  usageCount?: number | null;
  /**
   * Optional. Caps how many times the same customer email can use this code.
   */
  maxRedemptionsPerEmail?: number | null;
  /**
   * Uncheck to make this code invalid for Angola orders.
   */
  availableAO?: boolean | null;
  /**
   * Uncheck to make this code invalid for Portugal orders.
   */
  availablePT?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'merch-tags';
        value: number | MerchTag;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'size-guides';
        value: number | SizeGuide;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  namePT?: T;
  nameEN?: T;
  slug?: T;
  category?: T;
  description?: T;
  descriptionPT?: T;
  descriptionEN?: T;
  sizeGuide?: T;
  fitNotePT?: T;
  fitNoteEN?: T;
  tag?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  priceAOKz?: T;
  pricePTEur?: T;
  shippingWeightGrams?: T;
  saleAOKz?: T;
  salePTEur?: T;
  saleStartDate?: T;
  saleEndDate?: T;
  variants?:
    | T
    | {
        color?: T;
        size?: T;
        stockAO?: T;
        stockPT?: T;
        id?: T;
      };
  active?: T;
  availableAO?: T;
  availablePT?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  namePT?: T;
  nameEN?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch-tags_select".
 */
export interface MerchTagsSelect<T extends boolean = true> {
  labelPT?: T;
  labelEN?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  namePT?: T;
  nameEN?: T;
  hex?: T;
  hex2?: T;
  swatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-guides_select".
 */
export interface SizeGuidesSelect<T extends boolean = true> {
  name?: T;
  rows?:
    | T
    | {
        size?: T;
        bust?: T;
        waist?: T;
        hip?: T;
        length?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  market?: T;
  status?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  analyticsConsent?: T;
  metaFbp?: T;
  metaFbc?: T;
  metaEventSourceUrl?: T;
  lang?: T;
  address?: T;
  addressLine2?: T;
  postalCode?: T;
  deliveryRegion?: T;
  city?: T;
  country?: T;
  taxId?: T;
  notes?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        size?: T;
        color?: T;
        colorId?: T;
        qty?: T;
        unitPrice?: T;
        id?: T;
      };
  currency?: T;
  subtotal?: T;
  shippingCost?: T;
  couponCode?: T;
  discountAmount?: T;
  discountLabel?: T;
  total?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  inventoryReservationStatus?: T;
  inventoryReservationExpiresAt?: T;
  inventoryReservationReleasedAt?: T;
  deliveryMethod?: T;
  cttTrackingCode?: T;
  paymentReference?: T;
  appyPayMerchantTransactionId?: T;
  appyPayTransactionId?: T;
  appyPayStatus?: T;
  appyPayPaymentMethod?: T;
  appyPayResponseCode?: T;
  appyPayResponseMessage?: T;
  appyPayReferenceEntity?: T;
  appyPayReferenceNumber?: T;
  appyPayReferenceDueDate?: T;
  appyPayVerifiedAt?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        changedBy?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  market?: T;
  orderCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  channel?: T;
  direction?: T;
  contactHandle?: T;
  customerName?: T;
  body?: T;
  status?: T;
  automationNote?: T;
  relatedOrder?: T;
  relatedCustomer?: T;
  sentByAutomation?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  relatedOrder?: T;
  invoiceNumber?: T;
  sequence?: T;
  year?: T;
  status?: T;
  market?: T;
  issuedAt?: T;
  orderNumber?: T;
  issuerName?: T;
  issuerTaxId?: T;
  issuerAddress?: T;
  bankName?: T;
  accountHolder?: T;
  bankAccount?: T;
  swiftBic?: T;
  paymentInstructions?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerTaxId?: T;
  customerAddress?: T;
  lines?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        netAmount?: T;
        taxAmount?: T;
        grossAmount?: T;
        id?: T;
      };
  currency?: T;
  vatRate?: T;
  taxNote?: T;
  subtotal?: T;
  shipping?: T;
  netTotal?: T;
  taxTotal?: T;
  total?: T;
  paymentMethod?: T;
  paymentReference?: T;
  disclaimer?: T;
  footer?: T;
  pdfFilename?: T;
  pdfData?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  active?: T;
  description?: T;
  type?: T;
  percentOff?: T;
  fixedOffAOKz?: T;
  fixedOffPTEur?: T;
  minOrderValueAOKz?: T;
  minOrderValuePTEur?: T;
  startDate?: T;
  endDate?: T;
  usageLimit?: T;
  usageCount?: T;
  maxRedemptionsPerEmail?: T;
  availableAO?: T;
  availablePT?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings".
 */
export interface MarketSetting {
  id: number;
  /**
   * Turn ON only after the AppyPay application and webhook are operational. Stripe/PayPal for Angola are unaffected because they use the separate EUR settlement path.
   */
  angolaPaymentLive?: boolean | null;
  /**
   * Shown at checkout while angolaPaymentLive is off (e.g. "As instruções de pagamento são enviadas por WhatsApp assim que a encomenda for confirmada").
   */
  angolaBankTransferInstructionsPT?: string | null;
  /**
   * English translation of the field above (e.g. "Payment instructions are sent by WhatsApp once the order is confirmed").
   */
  angolaBankTransferInstructionsEN?: string | null;
  angolaPaymentMethods?: ('multicaixa_express' | 'stripe' | 'paypal')[] | null;
  angolaDeliveryMethods?: 'courier_ao'[] | null;
  /**
   * Placeholder local-courier prices. Edit the Kz value for any municipality; keep all 16 keys.
   */
  angolaMunicipalityPrices:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Applied to the merchandise total after discounts.
   */
  angolaFreeShippingThreshold: number;
  /**
   * Keep OFF until the Portuguese legal entity, invoicing process, and payment-provider accounts are approved. Turning this on re-enables PT checkout.
   */
  portugalPaymentsEnabled?: boolean | null;
  portugalPaymentMethods?: ('paypal' | 'stripe' | 'mbway')[] | null;
  portugalDeliveryMethods?: ('ctt' | 'courier_pt')[] | null;
  /**
   * Customer charge for the untracked option below the free-delivery threshold.
   */
  portugalStandardShippingPrice: number;
  /**
   * Customer charge for tracked CTT delivery below the free-delivery threshold.
   */
  portugalTrackedShippingPrice: number;
  /**
   * Applied to the merchandise total after coupons and other discounts.
   */
  portugalFreeShippingThreshold: number;
  portugalStandardWeightLimitGrams: number;
  portugalHeavyMainlandShippingPrice: number;
  portugalHeavyIslandsShippingPrice: number;
  /**
   * Client-provided legal copy (JOS-64, added 2026-07-23). Angola’s policy differs materially from Portugal’s (48h exchange window, no refunds) so it is a separate field rather than a shared translation.
   */
  angolaReturnsPolicyTextPT?: string | null;
  /**
   * English translation of the field above (JOS-64, added 2026-07-24), so the policy is bilingual like the rest of the storefront.
   */
  angolaReturnsPolicyTextEN?: string | null;
  /**
   * Client-provided legal copy (JOS-64, added 2026-07-23). 14-day EU distance-selling withdrawal window.
   */
  portugalReturnsPolicyTextPT?: string | null;
  /**
   * English translation of the field above (JOS-64, added 2026-07-24), so the policy is bilingual like the rest of the storefront.
   */
  portugalReturnsPolicyTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  businessHoursTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  businessHoursTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  angolaShippingTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  angolaShippingTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  portugalShippingTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  portugalShippingTextEN?: string | null;
  /**
   * Client-provided copy, added 2026-07-24.
   */
  internationalShippingTextPT?: string | null;
  /**
   * English translation of the field above, added 2026-07-24.
   */
  internationalShippingTextEN?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phase 1 commercial documents for accounting support. These settings are snapshotted onto each invoice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-settings".
 */
export interface InvoiceSetting {
  id: number;
  phaseOneDisclaimerPT: string;
  phaseOneDisclaimerEN: string;
  invoicingEnabledAO?: boolean | null;
  issuerNameAO?: string | null;
  issuerTaxIdAO?: string | null;
  issuerAddressAO?: string | null;
  bankNameAO?: string | null;
  accountHolderAO?: string | null;
  bankAccountAO?: string | null;
  swiftBicAO?: string | null;
  paymentInstructionsAO?: string | null;
  /**
   * The paid total never changes. This rate extracts the VAT portion already included in the price.
   */
  vatRateAO?: number | null;
  /**
   * Optional note supplied by the accountant.
   */
  taxNoteAO?: string | null;
  invoicePrefixAO?: string | null;
  invoiceFooterAO?: string | null;
  invoicingEnabledPT?: boolean | null;
  issuerNamePT?: string | null;
  issuerTaxIdPT?: string | null;
  issuerAddressPT?: string | null;
  bankNamePT?: string | null;
  accountHolderPT?: string | null;
  bankAccountPT?: string | null;
  swiftBicPT?: string | null;
  paymentInstructionsPT?: string | null;
  /**
   * The paid total never changes. This rate extracts the VAT portion already included in the price.
   */
  vatRatePT?: number | null;
  /**
   * Optional note supplied by the accountant.
   */
  taxNotePT?: string | null;
  invoicePrefixPT?: string | null;
  invoiceFooterPT?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Privacy Policy and Terms & Conditions shown on the storefront. The seeded text is an AI-drafted generic template -- have it reviewed by a lawyer before treating it as final.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-content".
 */
export interface LegalContent {
  id: number;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  privacyPolicyTextPT?: string | null;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  privacyPolicyTextEN?: string | null;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  termsTextPT?: string | null;
  /**
   * AI-drafted generic template, added 2026-07-24. Needs legal review before final.
   */
  termsTextEN?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable content for the storefront home page's hero banner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  /**
   * Small label above the headline, e.g. "Coleção SS26".
   */
  heroEyebrowPT?: string | null;
  heroEyebrowEN?: string | null;
  heroHeadlinePT?: string | null;
  heroHeadlineEN?: string | null;
  heroSubtitlePT?: string | null;
  heroSubtitleEN?: string | null;
  heroCtaLabelPT?: string | null;
  heroCtaLabelEN?: string | null;
  /**
   * Where the hero button sends shoppers.
   */
  heroCtaType?: ('all' | 'category' | 'tag') | null;
  /**
   * Only used when link type is "One category".
   */
  heroCtaCategorySlug?: string | null;
  /**
   * Only used when link type is "Merchandising tag". Pick a tag on the right.
   */
  heroCtaTagSlug?: string | null;
  /**
   * Optional. Replaces the decorative placeholder graphic on the right of the hero banner when set.
   */
  heroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "market-settings_select".
 */
export interface MarketSettingsSelect<T extends boolean = true> {
  angolaPaymentLive?: T;
  angolaBankTransferInstructionsPT?: T;
  angolaBankTransferInstructionsEN?: T;
  angolaPaymentMethods?: T;
  angolaDeliveryMethods?: T;
  angolaMunicipalityPrices?: T;
  angolaFreeShippingThreshold?: T;
  portugalPaymentsEnabled?: T;
  portugalPaymentMethods?: T;
  portugalDeliveryMethods?: T;
  portugalStandardShippingPrice?: T;
  portugalTrackedShippingPrice?: T;
  portugalFreeShippingThreshold?: T;
  portugalStandardWeightLimitGrams?: T;
  portugalHeavyMainlandShippingPrice?: T;
  portugalHeavyIslandsShippingPrice?: T;
  angolaReturnsPolicyTextPT?: T;
  angolaReturnsPolicyTextEN?: T;
  portugalReturnsPolicyTextPT?: T;
  portugalReturnsPolicyTextEN?: T;
  businessHoursTextPT?: T;
  businessHoursTextEN?: T;
  angolaShippingTextPT?: T;
  angolaShippingTextEN?: T;
  portugalShippingTextPT?: T;
  portugalShippingTextEN?: T;
  internationalShippingTextPT?: T;
  internationalShippingTextEN?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-settings_select".
 */
export interface InvoiceSettingsSelect<T extends boolean = true> {
  phaseOneDisclaimerPT?: T;
  phaseOneDisclaimerEN?: T;
  invoicingEnabledAO?: T;
  issuerNameAO?: T;
  issuerTaxIdAO?: T;
  issuerAddressAO?: T;
  bankNameAO?: T;
  accountHolderAO?: T;
  bankAccountAO?: T;
  swiftBicAO?: T;
  paymentInstructionsAO?: T;
  vatRateAO?: T;
  taxNoteAO?: T;
  invoicePrefixAO?: T;
  invoiceFooterAO?: T;
  invoicingEnabledPT?: T;
  issuerNamePT?: T;
  issuerTaxIdPT?: T;
  issuerAddressPT?: T;
  bankNamePT?: T;
  accountHolderPT?: T;
  bankAccountPT?: T;
  swiftBicPT?: T;
  paymentInstructionsPT?: T;
  vatRatePT?: T;
  taxNotePT?: T;
  invoicePrefixPT?: T;
  invoiceFooterPT?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-content_select".
 */
export interface LegalContentSelect<T extends boolean = true> {
  privacyPolicyTextPT?: T;
  privacyPolicyTextEN?: T;
  termsTextPT?: T;
  termsTextEN?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  heroEyebrowPT?: T;
  heroEyebrowEN?: T;
  heroHeadlinePT?: T;
  heroHeadlineEN?: T;
  heroSubtitlePT?: T;
  heroSubtitleEN?: T;
  heroCtaLabelPT?: T;
  heroCtaLabelEN?: T;
  heroCtaType?: T;
  heroCtaCategorySlug?: T;
  heroCtaTagSlug?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}